### ISSUE TITLE
Failed to run v2ray-plugin with -f parameter

### ISSUE THREAD

**Issue by poplite** [shadowsocks/v2ray-plugin#29]
```
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin v2ray-plugin --plugin-opts "server" -f /tmp/test.pid
user@localhost:~$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 16:13:25 localhost ss-server[16625]: plugin "v2ray-plugin" enabled
Jan 28 16:13:25 localhost ss-server[16625]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 16:13:25 localhost ss-server[16625]: tcp server listening at 127.0.0.1:34139
Jan 28 16:13:25 localhost ss-server[16625]: plugin service exit unexpectedly
Jan 28 16:13:25 localhost ss-server[16625]: closed gracefully
```
It works fine without -f parameter:
```
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin v2ray-plugin --plugin-opts "server"
 2019-01-28 16:16:29 INFO: plugin "v2ray-plugin" enabled
 2019-01-28 16:16:29 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-01-28 16:16:29 INFO: tcp server listening at 127.0.0.1:33617
2019/01/28 16:16:29 V2Ray 4.13 (Po) Custom
2019/01/28 16:16:29 A unified platform for anti-censorship.
2019/01/28 16:16:29 [Warning] v2ray.com/core: V2Ray 4.13 started
```

obfs plugin works fine:
```
user@localhost:~$ ll $(which obfs-server)
-rwxr-xr-x 1 root root 412304 Mar 27  2018 /usr/local/bin/obfs-server*
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin obfs-server --plugin-opts "obfs=http" -f /tmp/test.pid
user@localhost:~$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 16:19:11 localhost ss-server[16758]: plugin "obfs-server" enabled
Jan 28 16:19:11 localhost ss-server[16758]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 16:19:11 localhost ss-server[16758]: tcp server listening at 127.0.0.1:50621
```
Proper permissions are set for  v2ray-plugin binary file:
```
user@localhost:~$ ll $(which v2ray-plugin)
-rwxr-xr-x 1 root root 3323584 Jan 19 22:00 /usr/local/bin/v2ray-plugin*
user@localhost:~$ getcap $(which v2ray-plugin)
/usr/local/bin/v2ray-plugin = cap_net_bind_service+ep
```

shadowsocks-libev: v3.2.3, built from latest source code
v2ray-plugin: v1.0, downloaded from Github's Release page
simple-obfs: v0.0.5, built from latest source code

**Comment by madeye** [comment]
Try 

```
ss-server -v -p 4433 -k XXX --plugin /usr/local/bin/v2ray-plugin --plugin-opts "server" -f /tmp/test.pid
```

**Comment by poplite** [comment]
```
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin /usr/local/bin/v2ray-plugin --plugin-opts "server" -f /tmp/test.pid
user@localhost:~$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 19:47:32 localhost ss-server[3128]: plugin "/usr/local/bin/v2ray-plugin" enabled
Jan 28 19:47:32 localhost ss-server[3128]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 19:47:32 localhost ss-server[3128]: tcp server listening at 127.0.0.1:41111
Jan 28 19:47:33 localhost ss-server[3128]: plugin service exit unexpectedly
Jan 28 19:47:33 localhost ss-server[3128]: closed gracefully
```
```
user@localhost:~$ sudo mv /usr/local/bin/v2ray-plugin /usr/bin
user@localhost:~$ which v2ray-plugin 
/usr/bin/v2ray-plugin
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin v2ray-plugin --plugin-opts "server" -f /tmp/test.pid
user@localhost:~$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 19:48:33 localhost ss-server[3164]: plugin "v2ray-plugin" enabled
Jan 28 19:48:33 localhost ss-server[3164]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 19:48:33 localhost ss-server[3164]: tcp server listening at 127.0.0.1:33415
Jan 28 19:48:33 localhost ss-server[3164]: plugin service exit unexpectedly
Jan 28 19:48:33 localhost ss-server[3164]: closed gracefully
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin /usr/bin/v2ray-plugin --plugin-opts "server" -f /tmp/test.pid
user@localhost:~$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 19:48:48 localhost ss-server[3181]: plugin "/usr/bin/v2ray-plugin" enabled
Jan 28 19:48:48 localhost ss-server[3181]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 19:48:48 localhost ss-server[3181]: tcp server listening at 127.0.0.1:51039
Jan 28 19:48:48 localhost ss-server[3181]: plugin service exit unexpectedly
Jan 28 19:48:48 localhost ss-server[3181]: closed gracefully
```
Still not working.

**Comment by poplite** [comment]
No more error messages from v2ray-plugin, even I add `loglevel=debug` to `--plugin-opts` parameter.

**Comment by poplite** [comment]
```
user@localhost:~$ ss-server -v -p 4433 -k XXX --plugin /usr/bin/v2ray-plugin --plugin-opts "server;loglevel=none" -f /tmp/test.pid
user@localhost:~$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 21:40:07 localhost ss-server[2995]: plugin "/usr/bin/v2ray-plugin" enabled
Jan 28 21:40:07 localhost ss-server[2995]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 21:40:07 localhost ss-server[2995]: tcp server listening at 127.0.0.1:47835
user@localhost:~$ ps -auxw | grep "ss-server"
user  2995  0.0  0.0  24900  2668 ?        Ss   21:40   0:00 ss-server -v -p 4433 -k XXX --plugin /usr/bin/v2ray-plugin --plugin-opts server;loglevel=none -f /tmp/test.pid
user  3008  0.0  0.0  16996   960 pts/3    S+   21:40   0:00 grep --color=auto ss-server
```
OK, it works now.

**Comment by madeye** [comment]
Also try https://github.com/shadowsocks/shadowsocks-libev/commit/333e98dc86fa085741c7f906f4ec146d46e0fd1c with your original `plugin-opts`.

**Comment by poplite** [comment]
```
user@localhost:~/shadowsocks-libev/src$ ./ss-server -v -p 4433 -k XXX --plugin v2ray-plugin --plugin-opts "server" -f /tmp/test.pid
user@localhost:~/shadowsocks-libev/src$ cat /var/log/syslog | grep $(cat /tmp/test.pid)
Jan 28 22:21:23 localhost ./ss-server[23463]: plugin "v2ray-plugin" enabled
Jan 28 22:21:23 localhost ./ss-server[23463]: initializing ciphers... chacha20-ietf-poly1305
Jan 28 22:21:23 localhost ./ss-server[23463]: tcp server listening at 127.0.0.1:50084
user@localhost:~/shadowsocks-libev/src$ ps -auxw | grep "ss-server"
user     23463  0.0  0.2  24916  2656 ?        Ss   22:21   0:00 ./ss-server -v -p 4433 -k XXX --plugin v2ray-plugin --plugin-opts server -f /tmp/test.pid
user     23476  0.0  0.1  14224  1016 pts/0    S+   22:21   0:00 grep --color=auto ss-server
```
Works with latest code. I think this bug is fixed.

**Comment by yujincheng08** [comment]
I am still facing the same issue. Nothing useful is in log, just saying plugin service exit unexpectedly. Not working with loglevel=debug nor loglevel=none.

**Comment by poplite** [comment]
@yujincheng08 Upgrade your shadowsocks, this issue was fixed by https://github.com/shadowsocks/shadowsocks-libev/commit/333e98dc86fa085741c7f906f4ec146d46e0fd1c

**Comment by yujincheng08** [comment]
@poplite Oh! I have to upgrade my shadosocks rather than the plugin!
However, it's not a good idea for me to compile and update shadowsocks because I installed it by apt. I would set the loglevel as a workaround.

**Comment by poplite** [comment]
@yujincheng08  What is the version of the shadowsocks you installed? [Shadowsocks](https://packages.ubuntu.com/bionic/shadowsocks-libev) from ubuntu official source is too old. Try to install it from [Max Lv's PPA](https://launchpad.net/~max-c-lv/+archive/ubuntu/shadowsocks-libev/+packages). 3.2.4 works fine for me.

**Comment by terrytw** [comment]
@madeye Same issue occured for ss-redir, and it is not fixed by 3.2.4. https://github.com/shadowsocks/v2ray-plugin/issues/55
